# Generated by Django 6.0 on 2026-02-07 18:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, default="", help_text="Optional user note"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                ("total_queries", models.PositiveIntegerField(default=0)),
                ("unique_users", models.PositiveIntegerField(default=0)),
                ("avg_trust_score", models.FloatField(default=0)),
                ("avg_response_time_ms", models.PositiveIntegerField(default=0)),
                (
                    "top_queries",
                    models.JSONField(
                        default=list, help_text="Top 10 queries of the day"
                    ),
                ),
                ("error_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Search analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default_max_sources", models.PositiveSmallIntegerField(default=10)),
                ("min_trust_score", models.PositiveSmallIntegerField(default=0)),
                (
                    "preferred_source_types",
                    models.JSONField(
                        default=list, help_text='e.g. ["academic","news","general"]'
                    ),
                ),
                ("enable_voice_search", models.BooleanField(default=True)),
                ("enable_auto_followups", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="searchquery",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Search queries",
            },
        ),
        migrations.AddField(
            model_name="searchquery",
            name="model_used",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="searchquery",
            name="response_time_ms",
            field=models.PositiveIntegerField(
                default=0, help_text="Response time in ms"
            ),
        ),
        migrations.AddField(
            model_name="searchquery",
            name="session_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Anon session identifier when user is not authenticated",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="searchquery",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="searchquery",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="searchquery",
            name="query",
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name="searchquery",
            name="trust_score",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="searchquery",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_queries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["user", "-created_at"], name="api_searchq_user_id_f771c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchquery",
            index=models.Index(
                fields=["session_key", "-created_at"],
                name="api_searchq_session_74fbca_idx",
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="search_query",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="api.searchquery",
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("search_query", "user"),
                name="unique_bookmark_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session_key__gt", "")),
                fields=("search_query", "session_key"),
                name="unique_bookmark_per_session",
            ),
        ),
    ]
