# Generated by Django 6.0 on 2026-07-15 18:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alertnotification_apikey_collectioncomment_factcheck_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("photography", "Photography"),
                            ("health", "Health"),
                            ("fitness", "Fitness"),
                            ("real_estate", "Real Estate"),
                            ("consulting", "Consulting"),
                            ("events", "Events"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=32,
                    ),
                ),
                ("schema_json", models.JSONField(default=dict)),
                ("thumbnail_url", models.URLField(blank=True, default="")),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_featured", "-usage_count", "name"],
            },
        ),
        migrations.AddField(
            model_name="form",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="form",
            name="settings_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="payment_amount",
            field=models.PositiveIntegerField(
                blank=True, help_text="Amount in cents", null=True
            ),
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="payment_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                    ("", "None"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="form",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="form",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="formsubmission",
            name="data",
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name="FormIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("google_sheets", "Google Sheets"),
                            ("notion", "Notion"),
                            ("webhook", "Webhook"),
                            ("stripe", "Stripe"),
                            ("email", "Email"),
                            ("zapier", "Zapier"),
                            ("slack", "Slack"),
                        ],
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("config", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="api.form",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("form", "integration_type")},
            },
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                            ("retrying", "Retrying"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "response_status_code",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_logs",
                        to="api.formintegration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
